services:
  zitadel:
    container_name: zitadel
    image: ghcr.io/zitadel/zitadel:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - zitadel
    env_file:
      - ./auth/.env
    command: start-from-init --tlsMode disabled --masterkeyFromEnv
    depends_on:
      zitadel-db:
        condition: "service_healthy"

  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:latest
    restart: unless-stopped
    ports:
      - "3592:3592"
    env_file:
      - ./auth/.env
    volumes:
      - ./cerbos:/policies
  zitadel-db:
    container_name: zitadel-db
    image: postgres:17
    restart: always
    env_file:
      - ./auth/.env
    volumes:
      - pgdata-zitadel:/var/lib/postgresql/data
    networks:
      - zitadel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  backend-db:
    container_name: backend-db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata-backend:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  pgdata-zitadel:
  pgdata-backend:
networks:
  zitadel:
  backend:
